import { ConsultantRoleDto } from "@/interfaces/ClinicalManagement/ConsultantRoleDto";
import { MedicationDosageDto } from "@/interfaces/ClinicalManagement/MedicationDosageDto";
import { MedicationFormDto } from "@/interfaces/ClinicalManagement/MedicationFormDto";
import { MedicationFrequencyDto } from "@/interfaces/ClinicalManagement/MedicationFrequencyDto";
import { MedicationGenericDto } from "@/interfaces/ClinicalManagement/MedicationGenericDto";
import { MedicationInstructionDto } from "@/interfaces/ClinicalManagement/MedicationInstructionDto";
import { MedicationRouteDto } from "@/interfaces/ClinicalManagement/MedicationRouteDto";
import { createEntityService } from "@/utils/Common/serviceFactory";
import { MedicationListDto } from "@/interfaces/ClinicalManagement/MedicationListDto";
import { OTProcedureListDto } from "@/interfaces/ClinicalManagement/ProcedureListDto";
import { IcdDetailDto } from "@/interfaces/ClinicalManagement/IcdDetailDto";
import { useMemo } from "react";
import { OPIPHistROSDto } from "@/interfaces/ClinicalManagement/OPIPHistROSDto";
import { OPIPHistPSHDto } from "@/interfaces/ClinicalManagement/OPIPHistPSHDto";
import { OPIPHistPMHDto } from "@/interfaces/ClinicalManagement/OPIPHistPMHDto";
import { OPIPHistSHDto } from "@/interfaces/ClinicalManagement/OPIPHistSHDto";
import { OPIPHistFHDto } from "@/interfaces/ClinicalManagement/OPIPHistFHDto";
import { DiagnosisDetailDto } from "@/interfaces/ClinicalManagement/DiagnosisDto";

export const medicationRouteService = useMemo(() => createEntityService<MedicationRouteDto>("MedicationRoute", "clinicalManagementURL"), []);
export const medicationFormService = useMemo(() => createEntityService<MedicationFormDto>("MedicationForm", "clinicalManagementURL"), []);
export const medicationGenericService = useMemo(() => createEntityService<MedicationGenericDto>("MedicationGeneric", "clinicalManagementURL"), []);
export const consultantRoleService = useMemo(() => createEntityService<ConsultantRoleDto>("ConsultantRole", "clinicalManagementURL"), []);
export const medicationDosageService = useMemo(() => createEntityService<MedicationDosageDto>("MedicationDosage", "clinicalManagementURL"), []);
export const medicationFrequencyService = useMemo(() => createEntityService<MedicationFrequencyDto>("MedicationFrequency", "clinicalManagementURL"), []);
export const medicationInstructionService = useMemo(() => createEntityService<MedicationInstructionDto>("MedicationInstruction", "clinicalManagementURL"), []);
export const medicationListService = useMemo(() => createEntityService<MedicationListDto>("MedicationList", "clinicalManagementURL"), []);
export const procedureListService = useMemo(() => createEntityService<OTProcedureListDto>("ProcedureList", "clinicalManagementURL"), []);
export const diagnosisListService = useMemo(() => createEntityService<IcdDetailDto>("IcdDetail", "clinicalManagementURL"), []);
export const reviewOfSystemService = useMemo(() => createEntityService<OPIPHistROSDto>("OPIPHistROS", "clinicalManagementURL"), []);
export const fhService = useMemo(() => createEntityService<OPIPHistFHDto>("OPIPHistFH", "clinicalManagementURL"), []);
export const shService = useMemo(() => createEntityService<OPIPHistSHDto>("OPIPHistSH", "clinicalManagementURL"), []);
export const pmhService = useMemo(() => createEntityService<OPIPHistPMHDto>("OPIPHistPMH", "clinicalManagementURL"), []);
export const rosService = useMemo(() => createEntityService<OPIPHistROSDto>("OPIPHistROS", "clinicalManagementURL"), []);
export const pshService = useMemo(() => createEntityService<OPIPHistPSHDto>("OPIPHistPSH", "clinicalManagementURL"), []);
export const icdDetailService = useMemo(() => createEntityService<DiagnosisDetailDto>("IcdDetail", "clinicalManagementURL"), []);
