export const LCENT_ID = {
  SINGLELINE_ALPHANUMERIC_VALUES: 2,
  SINGLELINE_NUMERIC_VALUES: 3,
  MULTILINE_VALUES: 4,
  MULTIPLE_SELECTION: 5,
  REFERENCE_VALUES: 6,
  TEMPLATE_VALUES: 7,
} as const;
